# DesEnchants Configuration

# Debug mode - shows extra information in console
debug-mode: false

# Maximum number of custom enchantments per item
max-enchantments: 5

# Whether to count vanilla enchantments towards the max limit
use-vanilla-enchantments: true

# Whether enchanted items should glow
enchantment-glow: true

# Success and destroy rates for enchantment books
enchantment-rates:
  # Default rates when not specified
  default:
    min-success: 50
    max-success: 80
    min-destroy: 10
    max-destroy: 30

  # Rates by rarity
  common:
    min-success: 70
    max-success: 90
    min-destroy: 5
    max-destroy: 15

  rare:
    min-success: 50
    max-success: 70
    min-destroy: 15
    max-destroy: 25

  epic:
    min-success: 30
    max-success: 50
    min-destroy: 20
    max-destroy: 35

  legendary:
    min-success: 20
    max-success: 40
    min-destroy: 25
    max-destroy: 40