name: DesEnchants
version: '${project.version}'
main: org.example.des.desEnchants.DesEnchants
api-version: '1.20'
commands:
  de:
    description: Main command for custom enchantments
    usage: /de [help|list|give|reload|apply|remove|info]
    aliases: [customenchants, enchants, desenchants, ce]
    permission: desenchants.use
    permission-message: You do not have permission to execute this command! (desenchants.use)